version: '3'

services:
  lambda-app:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./:/app
